const express = require('express');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const mongoose = require('mongoose');
const url = require('./config/db.js').url;
mongoose.connect(url);
const passport = require('passport');
const flash = require('connect-flash');
const Yelp = require('yelp');
const app = express();